---
kubernetes_binaries_info:
  install_path: /usr/bin
  tmp_download_path: /tmp/k8s_bins
  # Download link from here https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.13.md#downloads-for-v1130
  kubernetes_targz_link: https://dl.k8s.io/v1.13.0/kubernetes.tar.gz
  # Download link from here https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.13.md#node-binaries
  windows_bins_link: https://dl.k8s.io/v1.13.0/kubernetes-node-windows-amd64.tar.gz
  cni_linux_download_link: https://github.com/containernetworking/plugins/releases/download/v0.7.4/cni-plugins-amd64-v0.7.4.tgz

kubernetes_cluster_info:
  MASTER_IP: "{{MASTER_IP | default('master node does not need this')}}"
  CLUSTER_SUBNET: "{{CLUSTER_SUBNET}}"
  MASTER_INTERNAL_IP: "{{MASTER_INTERNAL_IP}}"
  SERVICE_CLUSTER_IP_RANGE: "{{SERVICE_CLUSTER_IP_RANGE}}"
  K8S_DNS_DOMAIN: "{{K8S_DNS_DOMAIN}}"
  K8S_DNS_SERVICE_IP: "{{K8S_DNS_SERVICE_IP}}"
  K8S_API_SERVICE_IP: "{{K8S_API_SERVICE_IP}}"
  ETCD_VERSION: "3.1.2"

kubernetes_certificates:
  tmp_generate_path: /tmp/k8s_certs
  directory: /etc/kubernetes/tls

kubernetes_binaries:
  linux_common:
    - kubectl
  linux_master:
    - kube-apiserver
    - kube-scheduler
    - kube-controller-manager
    - kubelet
    - kube-proxy
  linux_minion:
    - kubelet
    - kube-proxy
  windows:
    - kubelet.exe
    - kubectl.exe
    - kube-proxy.exe

kubernetes_dns:
  coredns_git_url: https://github.com/coredns/deployment
  tmp_path: /tmp
  branch: master

flannel_download_links:
  kube_flannel_vxlan: "https://raw.githubusercontent.com/e2e-win/flannel-kubernetes/master/misc/kube-flannel-vxlan.yml"
  kube_flannel_l2bridge: "https://raw.githubusercontent.com/e2e-win/flannel-kubernetes/master/misc/kube-flannel-l2bridge.yml"
  node_selector_patch: "https://raw.githubusercontent.com/Microsoft/SDN/master/Kubernetes/flannel/l2bridge/manifests/node-selector-patch.yml"
